/**
 * ダミーデータ。
 * ここを直接 import するのは src/lib/data.ts だけにする。
 * Phase 7 では data.ts の中身をSupabaseクエリに差し替えれば、画面側は無修正で済む。
 */
import type {
  Article,
  Board,
  Comment,
  FeedItem,
  Goal,
  Notification,
  RecordEntry,
  Review,
  Thread,
  ThreadReply,
  User,
  Work,
} from "./types";

export const users: User[] = [
  {
    id: "u1",
    username: "kineorama",
    displayName: "真夜中の映写技師",
    bio: "映画館の暗がりで生きています。週3本。ウォン・カーウァイとタル・ベーラの間で。",
    avatarHue: 12,
    followers: 824,
    following: 311,
  },
  {
    id: "u2",
    username: "nagisa_ink",
    displayName: "渚のインク",
    bio: "文学とレコードと余白。書くことは読み直すこと。",
    avatarHue: 168,
    followers: 1290,
    following: 402,
  },
  {
    id: "u3",
    username: "hakuchumu",
    displayName: "白昼夢書店",
    bio: "古書店の棚の隙間から。積読は約束であって負債ではない。",
    avatarHue: 42,
    followers: 567,
    following: 198,
  },
  {
    id: "u4",
    username: "noise_to_yohaku",
    displayName: "ノイズと余白",
    bio: "音像の話ばかりしています。ポストロック/アンビエント/歌謡曲。",
    avatarHue: 210,
    followers: 2103,
    following: 87,
  },
  {
    id: "u5",
    username: "alley_curator",
    displayName: "路地裏のキュレーター",
    bio: "展示と服と都市。見ることの訓練を続ける。",
    avatarHue: 300,
    followers: 940,
    following: 512,
  },
];

/** ログイン中ユーザー(モック) */
export const currentUser = users[0];

export const works: Work[] = [
  {
    id: "w1",
    title: "花様年華",
    category: "film",
    creator: "ウォン・カーウァイ",
    year: 2000,
    description:
      "1962年の香港。隣同士に越してきた男女が、互いの配偶者の不貞を知る。すれ違いと抑制の果てに残る、語られなかった恋の記録。",
    tags: ["香港映画", "恋愛", "60年代", "クリストファー・ドイル"],
    avgRating: 4.4,
    reviewCount: 128,
    recordCount: 542,
    coverFrom: "#7a1f1f",
    coverTo: "#2a0e0e",
  },
  {
    id: "w2",
    title: "ノルウェイの森",
    category: "literature",
    creator: "村上春樹",
    year: 1987,
    description:
      "「死は生の対極としてではなく、その一部として存在している」。喪失と再生をめぐる、永遠の青春小説。",
    tags: ["日本文学", "恋愛", "喪失"],
    avgRating: 3.9,
    reviewCount: 96,
    recordCount: 873,
    coverFrom: "#1f4a2e",
    coverTo: "#0e1f14",
  },
  {
    id: "w3",
    title: "犬王",
    category: "film",
    creator: "湯浅政明",
    year: 2022,
    description:
      "室町の世、異形の能楽師・犬王と盲目の琵琶法師・友魚。歴史から消された者たちの声が、ロックオペラとして蘇る。",
    tags: ["アニメーション", "音楽映画", "能楽"],
    avgRating: 4.1,
    reviewCount: 74,
    recordCount: 301,
    coverFrom: "#8a5a1f",
    coverTo: "#26160a",
  },
  {
    id: "w4",
    title: "LONG SEASON",
    category: "music",
    creator: "フィッシュマンズ",
    year: 1996,
    description:
      "35分1曲。反復と浮遊の果てに季節が巡る、日本のロック史に屹立する長編。深夜に聴くための音楽。",
    tags: ["日本のロック", "ダブ", "90年代"],
    avgRating: 4.7,
    reviewCount: 152,
    recordCount: 689,
    coverFrom: "#1f3a5e",
    coverTo: "#0c1626",
  },
  {
    id: "w5",
    title: "ゲルハルト・リヒター展",
    category: "exhibition",
    creator: "東京国立近代美術館",
    year: 2022,
    description:
      "フォト・ペインティングからアブストラクト・ペインティング、そして「ビルケナウ」へ。見ることの不可能性を見にいく展覧会。",
    tags: ["現代美術", "絵画", "ドイツ"],
    avgRating: 4.3,
    reviewCount: 41,
    recordCount: 188,
    coverFrom: "#5a5a5a",
    coverTo: "#1a1a1a",
  },
  {
    id: "w6",
    title: "百年の孤独",
    category: "literature",
    creator: "ガブリエル・ガルシア=マルケス",
    year: 1967,
    description:
      "蜃気楼の村マコンドとブエンディア一族、百年の物語。魔術的リアリズムの金字塔。",
    tags: ["ラテンアメリカ文学", "魔術的リアリズム"],
    avgRating: 4.5,
    reviewCount: 88,
    recordCount: 412,
    coverFrom: "#6e4a1f",
    coverTo: "#2a1c0c",
  },
  {
    id: "w7",
    title: "OK Computer",
    category: "music",
    creator: "Radiohead",
    year: 1997,
    description:
      "テクノロジーと疎外、来るべき世紀への予感。97年に鳴らされた、いまだ古びない警鐘。",
    tags: ["UKロック", "オルタナティブ", "90年代"],
    avgRating: 4.6,
    reviewCount: 134,
    recordCount: 758,
    coverFrom: "#2e4a6e",
    coverTo: "#111a26",
  },
  {
    id: "w8",
    title: "Yohji Yamamoto 2024-25AW",
    category: "fashion",
    creator: "Yohji Yamamoto",
    year: 2024,
    description:
      "黒、ドレープ、非対称。「完璧は醜い」という思想の最新形。パリで発表されたコレクション。",
    tags: ["モード", "黒", "パリコレ"],
    avgRating: 4.2,
    reviewCount: 23,
    recordCount: 95,
    coverFrom: "#262626",
    coverTo: "#0a0a0a",
  },
  {
    id: "w9",
    title: "ELDEN RING",
    category: "game",
    creator: "FromSoftware",
    year: 2022,
    description:
      "狭間の地を巡る褪せ人の旅。断片化された神話と、広大な孤独。死にながら読む物語。",
    tags: ["オープンワールド", "ダークファンタジー"],
    avgRating: 4.5,
    reviewCount: 67,
    recordCount: 350,
    coverFrom: "#4a4a2e",
    coverTo: "#16160c",
  },
  {
    id: "w10",
    title: "桜の園",
    category: "stage",
    creator: "アントン・チェーホフ / 新国立劇場",
    year: 2026,
    description:
      "失われゆく屋敷と桜の園。時代の変わり目に立ち尽くす人々の喜劇、あるいは悲劇。",
    tags: ["チェーホフ", "翻訳劇"],
    avgRating: 4.0,
    reviewCount: 18,
    recordCount: 64,
    coverFrom: "#6e2e4a",
    coverTo: "#260f1a",
  },
];

export const reviews: Review[] = [
  {
    id: "r1",
    workId: "w1",
    rating: 4.5,
    body: "狭い廊下、すれ違うときの一瞬の間合い、何度も繰り返される「Yumeji's Theme」。語らないことで語る映画の極北。マギー・チャンのチャイナドレスは衣装ではなく時間の装置だと思う。ラストのアンコールワットで、この映画は恋愛映画から祈りに変わる。",
    spoiler: false,
    axes: [
      { axis: "映像", score: 10 },
      { axis: "脚本", score: 8 },
      { axis: "演技", score: 9 },
      { axis: "音楽", score: 9 },
      { axis: "余韻", score: 10 },
    ],
    tags: ["再鑑賞", "深夜に観るべき"],
    likes: 84,
    comments: 12,
    visibility: "public",
  },
  {
    id: "r2",
    workId: "w4",
    rating: 5,
    body: "35分が一瞬で過ぎる、というのは正確ではない。35分の中に一つの季節が丸ごと入っている。ループするピアノ、佐藤伸治の声の遠さ。「ズームしていく」感覚を音楽で体験できる稀有な作品。イヤホンではなくスピーカーで、部屋を暗くして。",
    spoiler: false,
    axes: [
      { axis: "メロディ", score: 9 },
      { axis: "歌詞", score: 8 },
      { axis: "音像", score: 10 },
      { axis: "革新性", score: 10 },
      { axis: "中毒性", score: 10 },
    ],
    tags: ["名盤", "夜"],
    likes: 132,
    comments: 21,
    visibility: "public",
  },
  {
    id: "r3",
    workId: "w2",
    rating: 4,
    body: "再読。20歳のときは直子の物語として読んだが、いまは緑の物語として読める。「春の熊くらい好き」という台詞の軽さが、この小説の死の重さとちょうど釣り合っている。井戸の話を冒頭に置いた構成の周到さに改めて唸る。",
    spoiler: true,
    axes: [
      { axis: "文体", score: 9 },
      { axis: "構成", score: 9 },
      { axis: "思想", score: 7 },
      { axis: "人物", score: 8 },
      { axis: "余白", score: 9 },
    ],
    tags: ["再読", "村上春樹"],
    likes: 56,
    comments: 9,
    visibility: "public",
  },
  {
    id: "r4",
    workId: "w5",
    rating: 4.5,
    body: "「ビルケナウ」の前で動けなくなった。描くことの不可能性を描くという矛盾を、リヒターは絵具の層で物理的に見せる。撮影可の喧騒と、あの一室の静けさの落差も含めて展示だったと思う。",
    spoiler: false,
    axes: [
      { axis: "企画", score: 9 },
      { axis: "空間", score: 8 },
      { axis: "作品", score: 10 },
      { axis: "解説", score: 7 },
      { axis: "余韻", score: 10 },
    ],
    tags: ["現代美術"],
    likes: 47,
    comments: 6,
    visibility: "public",
  },
  {
    id: "r5",
    workId: "w7",
    rating: 5,
    body: "「Fitter Happier」の合成音声が予言した世界に、私たちはもう住んでいる。Paranoid Androidの構成は何度聴いても建築。97年のアルバムが2026年の不安を一番正確に言い当てているのは、皮肉ではなく批評の勝利。",
    spoiler: false,
    axes: [
      { axis: "メロディ", score: 9 },
      { axis: "歌詞", score: 10 },
      { axis: "音像", score: 9 },
      { axis: "革新性", score: 10 },
      { axis: "中毒性", score: 8 },
    ],
    tags: ["名盤"],
    likes: 98,
    comments: 15,
    visibility: "public",
  },
];

/** 鑑賞ログ。直近2ヶ月ぶんを中心に(カレンダー・統計用) */
export const records: RecordEntry[] = [
  { id: "rec1", workId: "w1", status: "done", date: "2026-06-10T22:30:00+09:00", durationMinutes: 98, memo: "三度目。雨の日に観ると沁みる。", emotionTags: ["静かに効いた"], place: "自宅", visibility: "public" },
  { id: "rec2", workId: "w2", status: "doing", date: "2026-06-09T23:00:00+09:00", pages: 86, memo: "上巻の半分まで。", emotionTags: ["考え込んだ"], visibility: "public" },
  { id: "rec3", workId: "w4", status: "done", date: "2026-06-08T01:10:00+09:00", tracks: 1, durationMinutes: 35, memo: "深夜1時、消灯して。", emotionTags: ["震えた"], place: "自宅", visibility: "public" },
  { id: "rec4", workId: "w5", status: "done", date: "2026-06-07T15:00:00+09:00", durationMinutes: 140, memo: "ビルケナウの部屋に30分いた。", emotionTags: ["途方に暮れた"], place: "竹橋", visibility: "public" },
  { id: "rec5", workId: "w9", status: "doing", date: "2026-06-06T21:00:00+09:00", durationMinutes: 120, memo: "リエーニエ突入。", emotionTags: ["ざわついた"], visibility: "private" },
  { id: "rec6", workId: "w6", status: "stacked", date: "2026-06-05T10:00:00+09:00", memo: "文庫で買い直した。今度こそ。", emotionTags: [], visibility: "public" },
  { id: "rec7", workId: "w3", status: "done", date: "2026-06-03T19:30:00+09:00", durationMinutes: 98, memo: "劇場リバイバル。音響が違う。", emotionTags: ["震えた"], place: "新宿", visibility: "public" },
  { id: "rec8", workId: "w7", status: "done", date: "2026-06-02T08:00:00+09:00", tracks: 12, durationMinutes: 53, memo: "通勤で通して。", emotionTags: ["考え込んだ"], visibility: "public" },
  { id: "rec9", workId: "w10", status: "want", date: "2026-06-01T12:00:00+09:00", memo: "チケット取れた。月末。", emotionTags: [], visibility: "public" },
  { id: "rec10", workId: "w2", status: "doing", date: "2026-05-30T22:00:00+09:00", pages: 54, emotionTags: [], visibility: "public" },
  { id: "rec11", workId: "w1", status: "done", date: "2026-05-26T23:00:00+09:00", durationMinutes: 98, emotionTags: ["泣いた"], visibility: "public" },
  { id: "rec12", workId: "w4", status: "done", date: "2026-05-24T00:30:00+09:00", durationMinutes: 35, tracks: 1, emotionTags: ["静かに効いた"], visibility: "public" },
  { id: "rec13", workId: "w8", status: "done", date: "2026-05-20T14:00:00+09:00", durationMinutes: 40, memo: "アーカイブ映像で。黒の解像度。", emotionTags: ["ざわついた"], visibility: "public" },
  { id: "rec14", workId: "w9", status: "doing", date: "2026-05-18T21:30:00+09:00", durationMinutes: 180, emotionTags: [], visibility: "private" },
  { id: "rec15", workId: "w6", status: "want", date: "2026-05-15T09:00:00+09:00", emotionTags: [], visibility: "public" },
  { id: "rec16", workId: "w7", status: "done", date: "2026-05-12T19:00:00+09:00", tracks: 12, durationMinutes: 53, emotionTags: ["考え込んだ"], visibility: "public" },
  { id: "rec17", workId: "w3", status: "rewatch", date: "2026-05-10T20:00:00+09:00", emotionTags: [], visibility: "public" },
  { id: "rec18", workId: "w5", status: "want", date: "2026-05-08T11:00:00+09:00", emotionTags: [], visibility: "public" },
];

export const articles: Article[] = [
  {
    id: "a1",
    title: "語らないことの技法 — ウォン・カーウァイと省略の美学",
    excerpt:
      "『花様年華』には決定的な場面がことごとく映らない。不貞の現場も、告白も、別れも。なぜ省略は雄弁になりうるのか。小津、ブレッソンを補助線に考える。",
    body: "『花様年華』には決定的な場面がことごとく映らない。不貞の現場も、告白も、別れも。\n\nなぜ省略は雄弁になりうるのか。\n\n## 映らないものの重力\n\n映画は本来「映す」装置である。にもかかわらず、映さないことを選択した瞬間、観客の想像力が画面の外に動員される。ウォン・カーウァイはこの「画面外の重力」を誰よりも信頼した作家だ。\n\n小津安二郎が結婚式を映さず、ブレッソンが死を直接見せなかったように、省略は怠慢ではなく設計である。\n\n## 反復という時間の編集\n\n同じ階段、同じ麺の屋台、同じ音楽。反復されるたびに、わずかな差異が際立つ。私たちは差異によってしか時間の経過を知覚できない。\n\n## 結論にかえて\n\n語らないことは、語ることより多くの読者を信頼する行為である。批評もまた、そうありたい。",
    tags: ["映画批評", "ウォン・カーウァイ", "省略"],
    readMinutes: 8,
    likes: 210,
    comments: 34,
    coverFrom: "#7a1f1f",
    coverTo: "#1a0808",
    relatedWorkIds: ["w1"],
  },
  {
    id: "a2",
    title: "積読擁護論 — 読まれない本は死んでいるのか",
    excerpt:
      "積読を後ろめたさで語るのはもうやめよう。本棚の未読本は「可能性の在庫」であり、知の地図の余白である。ウンベルト・エーコの反図書館論から始める積読の哲学。",
    body: "積読を後ろめたさで語るのはもうやめよう。\n\n## 反図書館という考え方\n\nウンベルト・エーコは三万冊の蔵書を持っていた。訪問者は尋ねる。「全部読んだんですか?」エーコの答えはこうだ — 読んだ本を並べてどうする。図書館は、まだ読んでいない本のためにある。\n\nナシーム・タレブはこれを「反図書館(アンチライブラリー)」と呼んだ。未読の本は、自分の無知の輪郭を可視化する装置である。\n\n## 積読は約束である\n\n買うという行為は、未来の自分への手紙だ。いま読めなくても、いつか必要になる瞬間に、その本は棚で待っている。\n\n## 結論\n\n積読は負債ではなく投資である。堂々と積もう。",
    tags: ["読書論", "積読", "エッセイ"],
    readMinutes: 6,
    likes: 156,
    comments: 28,
    coverFrom: "#6e4a1f",
    coverTo: "#1a1208",
    relatedWorkIds: ["w6"],
  },
  {
    id: "a3",
    title: "35分間の季節 — フィッシュマンズ『LONG SEASON』構造分析",
    excerpt:
      "なぜこの曲は35分を必要としたのか。5つのパートの円環構造、ダブ処理された空間、そして「ループ」という思想。聴くたびに違う場所に連れていかれる理由を、構造から解く。",
    body: "なぜこの曲は35分を必要としたのか。\n\n## 円環としての構成\n\n『LONG SEASON』は5つのパートからなる。冒頭のピアノのリフレインは終盤で回帰するが、同じものとしてではない。一周してきた聴き手の耳が変わっているからだ。\n\n## ダブという空間処理\n\n音が消える瞬間の残響。フィッシュマンズの音像は「音が鳴っている場所」ではなく「音が消えていく場所」を聴かせる。\n\n## ループの思想\n\n反復は停滞ではない。季節が巡るように、同じ場所に戻ってくることでしか確認できない変化がある。",
    tags: ["音楽批評", "フィッシュマンズ", "構造分析"],
    readMinutes: 11,
    likes: 187,
    comments: 19,
    coverFrom: "#1f3a5e",
    coverTo: "#0a1220",
    relatedWorkIds: ["w4"],
  },
];

export const boards: Board[] = [
  { id: "b1", name: "映画板", description: "新作旧作問わず。ネタバレはスレッドのルールに従って。", category: "film", threadCount: 482 },
  { id: "b2", name: "文学板", description: "小説・詩・批評。再読の発見、翻訳の比較、なんでも。", category: "literature", threadCount: 391 },
  { id: "b3", name: "音楽板", description: "ジャンル不問。名盤語りからライブレポまで。", category: "music", threadCount: 530 },
  { id: "b4", name: "美術・展示板", description: "展覧会情報と感想。巡回情報の共有歓迎。", category: "exhibition", threadCount: 214 },
  { id: "b5", name: "ファッション板", description: "コレクション批評、ブランド史、装いの思想。", category: "fashion", threadCount: 158 },
  { id: "b6", name: "雑談板", description: "文化系の雑談すべて。今日観たもの聴いたもの。", category: "general", threadCount: 627 },
];

export const threads: Thread[] = [
  {
    id: "t1",
    boardId: "b1",
    title: "【ネタバレ可】『花様年華』のラストをどう解釈するか",
    body: "アンコールワットの穴に囁くシーン、初見から20年考え続けている。秘密を「葬る」行為だと思っていたが、最近は「保存」なのではと思い始めた。みんなの解釈を聞きたい。",
    replyCount: 47,
    anonymous: false,
    workId: "w1",
    createdAt: "2026-06-09T21:00:00+09:00",
    lastReplyAt: "2026-06-11T09:30:00+09:00",
  },
  {
    id: "t2",
    boardId: "b2",
    title: "村上春樹の「やれやれ」を真面目に数えるスレ",
    body: "全作品の「やれやれ」を数えて文脈ごとに分類しています。現在『ダンス・ダンス・ダンス』まで完了。協力者求む。",
    replyCount: 89,
    anonymous: true,
    workId: "w2",
    createdAt: "2026-06-07T13:00:00+09:00",
    lastReplyAt: "2026-06-10T23:10:00+09:00",
  },
  {
    id: "t3",
    boardId: "b3",
    title: "「夜に聴く一枚」を真剣に決めるスレ",
    body: "条件: 深夜0時以降、部屋を暗くして、通しで聴ける一枚。理由込みで頼む。",
    replyCount: 132,
    anonymous: true,
    createdAt: "2026-06-05T23:30:00+09:00",
    lastReplyAt: "2026-06-11T01:45:00+09:00",
  },
  {
    id: "t4",
    boardId: "b4",
    title: "2026年下半期、行くべき展示を挙げていく",
    body: "巡回情報・会期・混雑傾向もあれば。まず自分から: 7月の大阪中之島美術館。",
    replyCount: 28,
    anonymous: false,
    createdAt: "2026-06-08T10:00:00+09:00",
    lastReplyAt: "2026-06-10T18:00:00+09:00",
  },
];

export const threadReplies: ThreadReply[] = [
  { id: "tr1", threadId: "t1", number: 1, name: "真夜中の映写技師", body: "アンコールワットの穴に囁くシーン、初見から20年考え続けている。秘密を「葬る」行為だと思っていたが、最近は「保存」なのではと思い始めた。みんなの解釈を聞きたい。", likes: 21, createdAt: "2026-06-09T21:00:00+09:00" },
  { id: "tr2", threadId: "t1", number: 2, name: "名無しの批評家", body: "「葬る」と「保存」は対立しないのでは。墓は忘れるための装置じゃなくて、思い出すための場所だから。", likes: 34, createdAt: "2026-06-09T21:25:00+09:00" },
  { id: "tr3", threadId: "t1", number: 3, name: "渚のインク", body: ">>2 これに近い。あの穴は「誰にも読まれない手紙のポスト」だと思ってる。投函した時点で目的は達成されている。", quoteNumber: 2, likes: 28, createdAt: "2026-06-09T22:01:00+09:00" },
  { id: "tr4", threadId: "t1", number: 4, name: "名無しの批評家", body: "60年代の香港からカンボジアという場所の移動も効いてる。個人の秘密が歴史の遺跡に預けられる。私的な時間が公的な時間に接続される瞬間。", likes: 41, createdAt: "2026-06-10T00:13:00+09:00" },
  { id: "tr5", threadId: "t1", number: 5, name: "名無しの批評家", body: ">>4 その読みでいくと、『2046』が「預けた秘密を引き出しに戻る話」になるのが綺麗すぎる。", quoteNumber: 4, likes: 19, createdAt: "2026-06-10T08:40:00+09:00" },
  { id: "tr6", threadId: "t1", number: 6, name: "白昼夢書店", body: "穴に囁く行為自体、チャウが小説家だということと不可分だと思う。書けないことを物理的に「外部化」する。作家の業の話でもある。", likes: 15, createdAt: "2026-06-11T09:30:00+09:00" },
];

export const goals: Goal[] = [
  { id: "g1", title: "今月の映画", category: "film", period: "monthly", target: 10, current: 6, unit: "本" },
  { id: "g2", title: "年間読書", category: "literature", period: "yearly", target: 50, current: 23, unit: "冊" },
  { id: "g3", title: "週のアルバム", category: "music", period: "weekly", target: 3, current: 2, unit: "枚" },
  { id: "g4", title: "月の展示", category: "exhibition", period: "monthly", target: 2, current: 1, unit: "回" },
];

export const streakDays = 12;

/**
 * タイムライン。feed_items テーブルのモック。
 * 実装では posts/reviews/records... を作成したトリガーが行を追加する。
 */
export const feedItems: FeedItem[] = [
  {
    id: "f1",
    type: "post",
    user: users[1],
    createdAt: "2026-06-11T10:12:00+09:00",
    post: {
      id: "p1",
      body: "梅雨の古本市で濡れた箱の底から出てきた『百年の孤独』初版翻訳。雨の匂いとマコンドの湿気が混ざって、もうこれは運命の購入。",
      tags: ["古本", "百年の孤独"],
      likes: 42,
      reposts: 6,
      comments: 4,
      bookmarks: 11,
    },
  },
  {
    id: "f2",
    type: "review",
    user: users[0],
    createdAt: "2026-06-10T23:05:00+09:00",
    review: reviews[0],
    work: works[0],
  },
  {
    id: "f3",
    type: "record",
    user: users[2],
    createdAt: "2026-06-10T22:40:00+09:00",
    record: records[1],
    work: works[1],
  },
  {
    id: "f4",
    type: "thread",
    user: users[0],
    createdAt: "2026-06-09T21:00:00+09:00",
    thread: threads[0],
    board: boards[0],
  },
  {
    id: "f5",
    type: "article",
    user: users[1],
    createdAt: "2026-06-09T08:30:00+09:00",
    article: articles[0],
  },
  {
    id: "f6",
    type: "quote",
    user: users[3],
    createdAt: "2026-06-08T23:55:00+09:00",
    post: {
      id: "p2",
      body: "この「音が消えていく場所を聴かせる」という言い方、ダブの本質を一行で言い当てていてしばらく動けなかった。",
      tags: [],
      likes: 67,
      reposts: 14,
      comments: 3,
      bookmarks: 22,
    },
    quoted: {
      user: users[1],
      body: "フィッシュマンズの音像は「音が鳴っている場所」ではなく「音が消えていく場所」を聴かせる。",
      workTitle: "LONG SEASON",
    },
  },
  {
    id: "f7",
    type: "review",
    user: users[3],
    createdAt: "2026-06-08T01:50:00+09:00",
    review: reviews[1],
    work: works[3],
  },
  {
    id: "f8",
    type: "record",
    user: users[4],
    createdAt: "2026-06-07T16:20:00+09:00",
    record: records[3],
    work: works[4],
  },
  {
    id: "f9",
    type: "post",
    user: users[4],
    createdAt: "2026-06-07T12:00:00+09:00",
    post: {
      id: "p3",
      body: "展示の感想を「良かった」以外の言葉で言う練習を続けている。今日の収穫:「展示室の照度が作品の沈黙に合っていた」。言葉にすると見え方が変わる。",
      tags: ["見ることの訓練"],
      likes: 88,
      reposts: 19,
      comments: 7,
      bookmarks: 31,
    },
  },
  {
    id: "f10",
    type: "review",
    user: users[2],
    createdAt: "2026-06-06T20:15:00+09:00",
    review: reviews[2],
    work: works[1],
  },
  {
    id: "f11",
    type: "article",
    user: users[2],
    createdAt: "2026-06-06T09:00:00+09:00",
    article: articles[1],
  },
  {
    id: "f12",
    type: "thread",
    user: users[3],
    createdAt: "2026-06-05T23:30:00+09:00",
    thread: threads[2],
    board: boards[2],
  },
  {
    id: "f13",
    type: "record",
    user: users[0],
    createdAt: "2026-06-03T20:45:00+09:00",
    record: records[6],
    work: works[2],
  },
  {
    id: "f14",
    type: "article",
    user: users[3],
    createdAt: "2026-06-02T22:00:00+09:00",
    article: articles[2],
  },
  {
    id: "f15",
    type: "review",
    user: users[4],
    createdAt: "2026-06-01T18:30:00+09:00",
    review: reviews[3],
    work: works[4],
  },
  {
    id: "f16",
    type: "post",
    user: users[0],
    createdAt: "2026-06-01T00:20:00+09:00",
    post: {
      id: "p4",
      body: "6月の目標: 映画10本、うち未見の監督を3人。タイムラインに流れてきた知らない名前を拾っていく月にする。",
      tags: ["今月の目標"],
      likes: 25,
      reposts: 2,
      comments: 5,
      bookmarks: 8,
    },
  },
];

/** フィード項目IDごとのコメント(モック) */
export const comments: Record<string, Comment[]> = {
  f1: [
    {
      id: "c1",
      body: "雨に濡れた箱から出てくる本、一番いい出会い方ですね。",
      user: users[2],
      createdAt: "2026-06-11T11:00:00+09:00",
    },
    {
      id: "c2",
      body: "マコンドは常に湿気ているので正しい状態かもしれない。",
      user: users[3],
      createdAt: "2026-06-11T12:30:00+09:00",
    },
  ],
  f2: [
    {
      id: "c3",
      body: "「時間の装置」という言い方、すごくわかります。あの衣装は時計ですよね。",
      user: users[1],
      createdAt: "2026-06-11T00:10:00+09:00",
    },
  ],
};

export const notifications: Notification[] = [
  {
    id: "n1",
    kind: "like",
    actor: users[1],
    feedItemId: "f2",
    read: false,
    createdAt: "2026-06-11T09:00:00+09:00",
  },
  {
    id: "n2",
    kind: "comment",
    actor: users[3],
    feedItemId: "f2",
    read: false,
    createdAt: "2026-06-11T08:20:00+09:00",
  },
  {
    id: "n3",
    kind: "follow",
    actor: users[4],
    read: true,
    createdAt: "2026-06-10T22:00:00+09:00",
  },
  {
    id: "n4",
    kind: "like",
    actor: users[2],
    feedItemId: "f13",
    read: true,
    createdAt: "2026-06-09T19:45:00+09:00",
  },
];

export const trendingTags = [
  { tag: "花様年華", count: 482 },
  { tag: "夜に聴く一枚", count: 391 },
  { tag: "リヒター展", count: 233 },
  { tag: "積読擁護論", count: 187 },
  { tag: "今月の目標", count: 154 },
  { tag: "見ることの訓練", count: 112 },
];
